AUTHORIZATION = "authorization"
BODY = "body"
EXTRA_INFO = "extraInfo"
HEADERS = "headers"
INFO = "info"
LANG = "lang"
CURRENT_LANG = "currentlang"
DEFAULT_LANG = "en"
PARENT = "parent"
PROJECTID = "projectId"
REQUEST = "request"
SCOPE = "scope"
ID = "id"
_ID = "_id"
# -----------------COLLECTIONS--------------
COLLECTION_ERROR = "Error"
DATETIME = "%Y-%m-%dT%H:%M:%S.%fZ"
CRUDOPTIONS = "crudOptions"
